{
	"documenttitle": {
		"text": "Red Hat Security Advisory: python-django security update",
		"lang": "en"
	},
	"DocumentType": "Security Advisory",
	"documentpublisher": {
		"type": "Vendor",
		"ContactDetails": "secalert@redhat.com",
		"IssuingAuthority": "Red Hat Product Security"
	},
	"documenttracking": {
		"identification": {
			"ID": "RHSA-2020:4390"
		},
		"Status": "Final",
		"Version": "1",
		"revisionhistory": {
			"revision": {
				"Number": "1",
				"Date": "2020-10-28T18:24:00Z",
				"Description": "Current version"
			}
		},
		"InitialReleaseDate": "2020-10-28T18:24:00Z",
		"CurrentReleaseDate": "2020-10-28T18:24:00Z",
		"generator": {
			"Engine": "Red Hat SDEngine 3.0.0",
			"Date": "2021-08-23T04:49:00Z"
		}
	},
	"documentnotes": {
		"note": [
			{
				"text": "\nAn update for python-django is now available for Red Hat OpenStack Platform\n13 (Queens).\n\nRed Hat Product Security has rated this update as having a security impact\nof Moderate. A Common Vulnerability Scoring System (CVSS) base score, which\ngives a detailed severity rating, is available for each vulnerability from\nthe CVE link(s) in the References section.\n    ",
				"title": "Topic",
				"type": "Summary",
				"ordinal": "1",
				"lang": "en"
			},
			{
				"text": "\nDjango is a high-level Python Web framework that encourages rapid\ndevelopment and a clean, pragmatic design. It focuses on automating as much\nas possible and adhering to the DRY (Don't Repeat Yourself) principle.\n\nSecurity Fix(es):\n\n* Incorrect HTTP detection with reverse-proxy connecting via HTTPS\n(CVE-2019-12781)\n\n* backtracking in a regular expression in django.utils.text.Truncator leads\nto DoS (CVE-2019-14232)\n\n* the behavior of the underlying HTMLParser leading to DoS (CVE-2019-14233)\n\n* SQL injection possibility in key and index lookups for\nJSONField/HStoreField (CVE-2019-14234)\n\n* Potential memory exhaustion in django.utils.encoding.uri_to_iri()\n(CVE-2019-14235)\n\nFor more details about the security issue(s), including the impact, a CVSS\nscore, acknowledgments, and other related information, refer to the CVE\npage listed in the References section.\n    ",
				"title": "Details",
				"type": "General",
				"ordinal": "2",
				"lang": "en"
			},
			{
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use",
				"type": "Legal Disclaimer",
				"ordinal": "3",
				"lang": "en"
			}
		]
	},
	"documentdistribution": {
		"text": "Copyright Â© 2021 Red Hat, Inc. All rights reserved.",
		"lang": "en"
	},
	"aggregateseverity": {
		"text": "Moderate",
		"namespace": "https://access.redhat.com/security/updates/classification/"
	},
	"documentreferences": {
		"reference": [
			{
				"type": "Self",
				"URL": "https://access.redhat.com/errata/RHSA-2020:4390",
				"Description": "https://access.redhat.com/errata/RHSA-2020:4390"
			},
			{
				"type": "External",
				"URL": "https://access.redhat.com/security/updates/classification/#moderate",
				"Description": "https://access.redhat.com/security/updates/classification/#moderate"
			}
		]
	},
	"vulnerability": [
		{
			"ordinal": "1",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "Django: Incorrect HTTP detection with reverse-proxy connecting via HTTPS",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2019-07-01T00:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2019-12781",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2020:4390"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://www.djangoproject.com/weblog/2019/jul/01/security-releases/",
						"Description": "https://www.djangoproject.com/weblog/2019/jul/01/security-releases/"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2019-12781",
						"Description": "CVE-2019-12781"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1724497",
						"Description": "bz#1724497: CVE-2019-12781 Django: Incorrect HTTP detection with reverse-proxy connecting via HTTPS"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2019-06-24T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"7Server-7.6.EUS-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost",
						"7Server-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": "Red Hat would like to thank the Django project for reporting this issue. Upstream acknowledges Gavin Wahl as the original reporter."
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "2",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "Django: backtracking in a regular expression in django.utils.text.Truncator leads to DoS",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2019-08-01T08:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2019-14232",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2020:4390"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/",
						"Description": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2019-14232",
						"Description": "CVE-2019-14232"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1734405",
						"Description": "bz#1734405: CVE-2019-14232 Django: backtracking in a regular expression in django.utils.text.Truncator leads to DoS"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2019-07-25T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"7Server-7.6.EUS-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost",
						"7Server-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": "Red Hat would like to thank the Django project for reporting this issue."
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "3",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "Django: the behavior of the underlying HTMLParser leading to DoS",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2019-08-01T08:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2019-14233",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2020:4390"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/",
						"Description": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2019-14233",
						"Description": "CVE-2019-14233"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1734410",
						"Description": "bz#1734410: CVE-2019-14233 Django: the behavior of the underlying HTMLParser leading to DoS"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2019-07-25T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"7Server-7.6.EUS-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost",
						"7Server-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": "Red Hat would like to thank the Django project for reporting this issue."
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "4",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "Django: SQL injection possibility in key and index lookups for JSONField/HStoreField",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2019-08-01T08:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2019-14234",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2020:4390"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/",
						"Description": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2019-14234",
						"Description": "CVE-2019-14234"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1734417",
						"Description": "bz#1734417: CVE-2019-14234 Django: SQL injection possibility in key and index lookups for JSONField/HStoreField"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2019-07-25T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"7Server-7.6.EUS-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost",
						"7Server-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": "Red Hat would like to thank the Django project for reporting this issue."
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "5",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "Django: Potential memory exhaustion in django.utils.encoding.uri_to_iri()",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2019-08-01T08:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2019-14235",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2020:4390"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/",
						"Description": "https://www.djangoproject.com/weblog/2019/aug/01/security-releases/"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2019-14235",
						"Description": "CVE-2019-14235"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=1734422",
						"Description": "bz#1734422: CVE-2019-14235 Django: Potential memory exhaustion in django.utils.encoding.uri_to_iri()"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2019-07-25T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"7Server-7.6.EUS-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost",
						"7Server-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": "Red Hat would like to thank the Django project for reporting this issue."
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		}
	],
	"producttree": {
		"xmlns": "http://www.icasi.org/CVRF/schema/prod/1.1",
		"branch": [
			{
				"type": "Product Family",
				"name": "Red Hat OpenStack Platform",
				"branch": [
					{
						"type": "Product Name",
						"name": "Red Hat OpenStack Platform 13.0 for RHEL 7.6 EUS Server",
						"fullproductname": {
							"text": "Red Hat OpenStack Platform 13.0 for RHEL 7.6 EUS Server",
							"productid": "7Server-7.6.EUS-RH7-RHOS-13.0",
							"cpe": "cpe:/a:redhat:openstack:13::el7"
						}
					},
					{
						"type": "Product Name",
						"name": "Red Hat OpenStack Platform 13.0",
						"fullproductname": {
							"text": "Red Hat OpenStack Platform 13.0",
							"productid": "7Server-RH7-RHOS-13.0",
							"cpe": "cpe:/a:redhat:openstack:13::el7"
						}
					}
				],
				"fullproductname": {}
			},
			{
				"type": "Product Version",
				"name": "python-django-0:1.11.27-1.el7ost",
				"fullproductname": {
					"text": "python-django-1.11.27-1.el7ost.src.rpm",
					"productid": "python-django-0:1.11.27-1.el7ost",
					"cpe": "cpe:/a:redhat:openstack:13::el7"
				}
			}
		],
		"relationship": [
			{
				"productreference": "python-django-0:1.11.27-1.el7ost",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "7Server-7.6.EUS-RH7-RHOS-13.0",
				"fullproductname": {
					"text": "python-django-0:1.11.27-1.el7ost as a component of Red Hat OpenStack Platform 13.0 for RHEL 7.6 EUS Server",
					"productid": "7Server-7.6.EUS-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost",
					"cpe": "cpe:/a:redhat:openstack:13::el7"
				}
			},
			{
				"productreference": "python-django-0:1.11.27-1.el7ost",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "7Server-RH7-RHOS-13.0",
				"fullproductname": {
					"text": "python-django-0:1.11.27-1.el7ost as a component of Red Hat OpenStack Platform 13.0",
					"productid": "7Server-RH7-RHOS-13.0:python-django-0:1.11.27-1.el7ost",
					"cpe": "cpe:/a:redhat:openstack:13::el7"
				}
			}
		]
	}
}
